name: Deploy Strapi to ECS Fargate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      ECR_REPOSITORY: strapi
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/strapi:${{ env.IMAGE_TAG }} .

      # Push the Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/strapi:${{ env.IMAGE_TAG }}

      # Replace image tag in Terraform task definition
      - name: Update Terraform image tag
        run: |
          sed -i "s|image = \".*\"|image = \\\"${{ secrets.DOCKER_USERNAME }}/strapi:${{ env.IMAGE_TAG }}\\\"|g" terraform/ecs-service.tf

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Terraform Init
      - name: Terraform Init
        run: terraform -chdir=terraform init

      # Terraform Plan
      - name: Terraform Plan
        run: terraform -chdir=terraform plan

      # Terraform Apply
      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
`
