name: CD - Deploy to AWS

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  AWS_DEFAULT_REGION: eu-north-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy with Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -var="image_tag=${{ env.IMAGE_TAG }}" \
            -var="image_repo=${{ env.IMAGE_REPO }}"
        env:
          IMAGE_TAG: ${{ github.run_number }}
