name: CD - Deploy to AWS ECS

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  AWS_DEFAULT_REGION: eu-north-1
  IMAGE_REPO: zayn63/strapi  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy with Terraform
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -var="image_tag=${{ github.run_number }}" \
            -var="image_repo=${{ env.IMAGE_REPO }}"
